export const bdLocations = [
  { name: "Dhaka, Bangladesh" },
  { name: "Dhaka Division, Bangladesh" },
  { name: "Dhaka District, Dhaka" },
  { name: "Dhaka University, Nilkhet Road, Dhaka" },
  { name: "Dhaka Medical College Hospital, Dhaka" },
  { name: "Mirpur, Dhaka" },
  { name: "Mirpur-1, Dhaka" },
  { name: "Mirpur-2, Dhaka" },
  { name: "Banani, Dhaka" },
  { name: "Gulshan, Dhaka" },
  { name: "Dhanmondi, Dhaka" },
  { name: "Badda, Dhaka" },
  { name: "Jatrabari, Dhaka" },
  { name: "Uttara, Dhaka" },
  { name: "Motijheel, Dhaka" },
  { name: "Mohammadpur, Dhaka" },
  { name: "Rampura, Dhaka" },
  { name: "Tejgaon, Dhaka" },
  { name: "Khilgaon, Dhaka" },
  { name: "Shyamoli, Dhaka" },
  { name: "Paltan, Dhaka" },
  { name: "New Market, Dhaka" },
  { name: "Farmgate, Dhaka" },
  { name: "Kawran Bazar, Dhaka" },
  { name: "Bashundhara, Dhaka" },
  { name: "Adabor, Dhaka" },
  { name: "Kalabagan, Dhaka" },
  { name: "Mirpur-10, Dhaka" },
  { name: "Mirpur-11, Dhaka" },
  { name: "Uttara Sector-10, Dhaka" },
  { name: "Uttara Sector-11, Dhaka" },
  { name: "Uttara Sector-12, Dhaka" },
  { name: "Tejgaon Industrial Area, Dhaka" },
  { name: "Elephant Road, Dhaka" },
  { name: "Shahbagh, Dhaka" },
  { name: "Gulistan, Dhaka" },
  { name: "Savar, Dhaka" },
  { name: "Dhamrai, Dhaka" },
  { name: "Sutrapur, Dhaka" },
  { name: "Ramna, Dhaka" },
  { name: "Khilkhet, Dhaka" },
   { name: "Cumilla, Bangladesh" },
  { name: "Cumilla District, Cumilla" },
  { name: "Cumilla University, Cumilla" },
  { name: "Kotbari, Cumilla" },
  { name: "Debidwar, Cumilla" },
  { name: "Meghna, Cumilla" },
  { name: "Baroikhali, Cumilla" },
  { name: "Daudkandi, Cumilla" },
  { name: "Chandina, Cumilla" },
  { name: "Homna, Cumilla" },
  { name: "Muradnagar, Cumilla" },
  { name: "Titas, Cumilla" },
  { name: "Comilla Adarsha Sadar, Cumilla" },
  { name: "Cumilla Cantonment, Cumilla" },
  { name: "Shalbon, Cumilla" },
  { name: "Laksham, Cumilla" },
  { name: "Monohorgonj, Cumilla" },
  { name: "Nangalkot, Cumilla" },
  { name: "Chandpur Road, Cumilla" },
  { name: "Uttar Chak, Cumilla" },
  { name: "Motijheel, Cumilla" },
  { name: "Kanchanpur, Cumilla" },
  { name: "Debidwar Bazar, Cumilla" },
  { name: "Brahmanpara, Cumilla" },
  { name: "Shilmuri, Cumilla" },
  { name: "Rajapur, Cumilla" },
  { name: "Cumilla Medical College Area" },
  { name: "Chandina Bazar, Cumilla" },
  { name: "Chourashir Hat, Cumilla" },
  { name: "Cumilla Rail Station Area" },
  { name: "Cumilla Bus Terminal Area" },
  { name: "Naya Paltan, Cumilla" },
  { name: "Sadar Road, Cumilla" },
  { name: "Shahbazpur, Cumilla" },
  { name: "Madhabpur, Cumilla" },
  { name: "Shahjahanpur, Cumilla" },
  { name: "Cumilla Court Area" },
  { name: "Sadarghat, Cumilla" },
  { name: "Shahid Nagar, Cumilla" },
  { name: "Main Bazar, Cumilla" },
  { name: "Old Bus Stand, Cumilla" },
   { name: "Chittagong, Bangladesh" },
  { name: "Pahartali, Chittagong" },
  { name: "Agrabad, Chittagong" },
  { name: "Panchlaish, Chittagong" },
  { name: "Anderkilla, Chittagong" },
  { name: "Chawkbazar, Chittagong" },
  { name: "Halishahar, Chittagong" },
  { name: "Patenga, Chittagong" },
  { name: "Foy’s Lake Area, Chittagong" },
  { name: "Kaptai, Chittagong" },
  { name: "Nasirabad, Chittagong" },
  { name: "Muradpur, Chittagong" },
  { name: "GEC Circle, Chittagong" },
  { name: "Sholoshahar, Chittagong" },
  { name: "Bakalia, Chittagong" },
  { name: "Bayezid, Chittagong" },
  { name: "Kotwali, Chittagong" },
  { name: "Chandgaon, Chittagong" },
  { name: "Sitakunda, Chittagong" },
  { name: "Patiya, Chittagong" },
  { name: "Rangunia, Chittagong" },
  { name: "Anwara, Chittagong" },
  { name: "Banshkhali, Chittagong" },
  { name: "Fatikchhari, Chittagong" },
  { name: "Mirsharai, Chittagong" },
  { name: "Sandwip, Chittagong" },
  { name: "Hathazari, Chittagong" },
  { name: "Raozan, Chittagong" },
  { name: "Sitakunda Eco Park Area" },
  { name: "Tiger Pass, Chittagong" },
  { name: "Double Mooring, Chittagong" },
  { name: "Khulshi, Chittagong" },
  { name: "Nasirabad Bus Terminal Area" },
  { name: "Agrabad Commercial Area" },
  { name: "Jhautala, Chittagong" },
  { name: "Bakalia Bazar, Chittagong" },
  { name: "Anwara Industrial Area" },
  { name: "Patenga Beach Area" },
  { name: "Foy’s Lake Road, Chittagong" },
  { name: "GEC Circle Residential Area" },
  { name: "Sholoshahar Railway Area" },
  { name: "Panchlaish Residential Area" },
  { name: "Anderkilla Historic Area" },
  { name: "Chawkbazar Main Road" },
  { name: "Halishahar Residential Zone" },
  { name: "Kotwali Court Area" },
  { name: "Chittagong Port Area" },
  { name: "Pahartali Industrial Zone" },
  { name: "Muradpur Commercial Area" },
  { name: "Bayezid Residential Area" },
  { name: "Agrabad Backside Area" },
  { name: "Rajshahi, Bangladesh" },
  { name: "Motihar, Rajshahi" },
  { name: "Shah Mokhdum, Rajshahi" },
  { name: "Boalia, Rajshahi" },
  { name: "Shah Makhdum Airport Area, Rajshahi" },
  { name: "Kazla, Rajshahi" },
  { name: "Katakhali, Rajshahi" },
  { name: "Laxmipur, Rajshahi" },
  { name: "Shib Bari, Rajshahi" },
  { name: "Gopalpur, Rajshahi" },
  { name: "Chowk Bazar, Rajshahi" },
  { name: "Bagmara, Rajshahi" },
  { name: "Paba, Rajshahi" },
  { name: "Godagari, Rajshahi" },
  { name: "Tanore, Rajshahi" },
  { name: "Bagha, Rajshahi" },
  { name: "Bagmara Bazar, Rajshahi" },
  { name: "Rajshahi University Area" },
  { name: "Shaheed Chattar, Rajshahi" },
  { name: "Natore Road, Rajshahi" },
  { name: "Ranihat, Rajshahi" },
  { name: "Paba Bazar, Rajshahi" },
  { name: "Godagari Bazar, Rajshahi" },
  { name: "Tanore Bazar, Rajshahi" },
  { name: "Bagha Bazar, Rajshahi" },
  { name: "Boalia Bazar, Rajshahi" },
  { name: "Motihar Residential Area" },
  { name: "Shah Mokhdum Residential Area" },
  { name: "Kazla Residential Area" },
  { name: "Katakhali Residential Area" },
   { name: "Jessore, Bangladesh" },
  { name: "Shib Bari, Jessore" },
  { name: "Bagbari, Jessore" },
  { name: "Court Road, Jessore" },
  { name: "Chowgacha, Jessore" },
  { name: "Chanchra, Jessore" },
  { name: "Keshabpur, Jessore" },
  { name: "Manirampur, Jessore" },
  { name: "Abhaynagar, Jessore" },
  { name: "Jhikargachha, Jessore" },
  { name: "Sharsha, Jessore" },
  { name: "Bagharpara, Jessore" },
  { name: "Jessore Rail Station Area" },
  { name: "Jessore Bus Terminal Area" },
  { name: "New Market, Jessore" },
  { name: "Jessore Medical College Area" },
  { name: "Jessore Bazar, Jessore" },
  { name: "Jessore Sadar Road" },
  { name: "Jessore Cantonment Area" },
  { name: "Jashore Airport Area" },
  { name: "Jessore College Area" },
  { name: "Jessore Stadium Area" },
  { name: "Jessore Polytechnic Area" },
  { name: "Jessore Police Line Area" },
  { name: "Jessore Bus Stand Road" },
  { name: "Jessore Engineering College Area" },
  { name: "Jessore Stadium Road" },
  { name: "Jessore Shahi Bazar" },
  { name: "Jessore Residential Area" },
  { name: "Jessore Main Road Area" },
   { name: "Barishal, Bangladesh" },
  { name: "Kawser Bazar, Barishal" },
  { name: "Kazipur, Barishal" },
  { name: "Bakerganj, Barishal" },
  { name: "Banaripara, Barishal" },
  { name: "Wazirpur, Barishal" },
  { name: "Babuganj, Barishal" },
  { name: "Muladi, Barishal" },
  { name: "Mehendiganj, Barishal" },
  { name: "Agailjhara, Barishal" },
  { name: "Gaurnadi, Barishal" },
  { name: "Barishal University Area" },
  { name: "Barishal Medical College Area" },
  { name: "Bakerganj Bazar, Barishal" },
  { name: "Babuganj Bazar, Barishal" },
  { name: "Kawser Bazar Road, Barishal" },
  { name: "Banaripara Bazar, Barishal" },
  { name: "Muladi Bazar, Barishal" },
  { name: "Agailjhara Bazar, Barishal" },
  { name: "Wazirpur Bazar, Barishal" },
  { name: "Mehendiganj Bazar, Barishal" },
  { name: "Gaurnadi Bazar, Barishal" },
  { name: "Barishal Airport Area" },
  { name: "Barishal Sadar Road" },
  { name: "Barishal Stadium Area" },
  { name: "Barishal Port Area" },
  { name: "Barishal Residential Area" },
  { name: "Barishal Main Road" },
  { name: "Khalishpur, Barishal" },
  { name: "Barishal Bus Terminal Area" },
   { name: "Khulna, Bangladesh" },
  { name: "Daulatpur, Khulna" },
  { name: "Khalishpur, Khulna" },
  { name: "Sonadanga, Khulna" },
  { name: "Gollamari, Khulna" },
  { name: "Labanchara, Khulna" },
  { name: "Tala, Khulna" },
  { name: "Koyra, Khulna" },
  { name: "Batiaghata, Khulna" },
  { name: "Dumuria, Khulna" },
  { name: "Phultala, Khulna" },
  { name: "Terokhada, Khulna" },
  { name: "Paikgacha, Khulna" },
  { name: "Bagerhat Road, Khulna" },
  { name: "Khulna University Area" },
  { name: "Khulna Medical College Area" },
  { name: "Khulna Rail Station Area" },
  { name: "Khulna Bus Terminal Area" },
  { name: "Rupsha, Khulna" },
  { name: "Khalishpur Industrial Zone" },
  { name: "Gollamari Bazar, Khulna" },
  { name: "Sonadanga Residential Area" },
  { name: "Daulatpur Bazar, Khulna" },
  { name: "Labanchara Bazar, Khulna" },
  { name: "Phultala Bazar, Khulna" },
  { name: "Dumuria Bazar, Khulna" },
  { name: "Tala Bazar, Khulna" },
  { name: "Terokhada Bazar, Khulna" },
  { name: "Paikgacha Bazar, Khulna" },
  { name: "Batiaghata Bazar, Khulna" },
];


// Store ID: foodr68a5d1f3a54ec
// Store Password (API/Secret Key): foodr68a5d1f3a54ec@ssl


// Merchant Panel URL: https://sandbox.sslcommerz.com/manage/ (Credential as you inputted in the time of registration)


 
// Store name: testfoodrgqyq
// Registered URL: www.foodrush.com
// Session API to generate transaction: https://sandbox.sslcommerz.com/gwprocess/v3/api.php
// Validation API: https://sandbox.sslcommerz.com/validator/api/validationserverAPI.php?wsdl
// Validation API (Web Service) name: https://sandbox.sslcommerz.com/validator/api/validationserverAPI.php